# Generated by Django 4.2 on 2024-10-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authendicate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.BigIntegerField(
                default=1111111111,
                validators=[
                    django.core.validators.MinValueValidator(1111111111),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
    ]
