# Generated by Django 4.2 on 2024-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authendicate', '0002_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='customer_profile_images/default_img.png', null=True, upload_to='customer_profile_images/'),
        ),
    ]
