# Generated by Django 4.2 on 2024-01-20 12:27

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename)),
                ('status', models.BooleanField(default=False, help_text='0=show,1=Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='trend_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_top_title', models.CharField(max_length=255)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename)),
                ('product_title', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disc_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_decrip', models.TextField(max_length=5000)),
                ('status', models.BooleanField(default=False, help_text='0=show,1=Hidden')),
                ('trend', models.BooleanField(default=False, help_text='0=default,1=trend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
