# Generated by Django 4.2 on 2024-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_show",
            field=models.BooleanField(
                default=True, help_text="0 = Not show, 1 = Default"
            ),
        ),
    ]
