# Generated by Django 4.2 on 2024-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
