# Generated by Django 4.2 on 2024-10-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_view_count_delete_productviewcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
