# Generated by Django 4.2 on 2024-02-10 13:08

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcollection_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='image_product_2',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename),
        ),
    ]
