# Generated by Django 4.2 on 2024-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productcollection_image_product_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
