# Generated by Django 4.2 on 2024-10-26 08:35

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_category_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to=shop.models.getFilename),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to=shop.models.getFilename),
        ),
    ]
