# Generated by Django 4.2 on 2024-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
