# Generated by Django 4.2 on 2024-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productcollection_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default,1=trend'),
        ),
    ]
