# Generated by Django 4.2 on 2024-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_productreview_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
