# Generated by Django 5.0.1 on 2024-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
