# Generated by Django 4.2 on 2024-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='application',
        ),
        migrations.AddField(
            model_name='product',
            name='benifits_and_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recommandation',
            field=models.TextField(null=True),
        ),
    ]
