# Generated by Django 5.0.1 on 2024-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_quantity_cart_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(),
        ),
    ]
