# Generated by Django 4.2 on 2024-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_image1_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benifits_and_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommandation',
            field=models.TextField(),
        ),
    ]
