# Generated by Django 5.0.1 on 2024-06-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
