# Generated by Django 4.2 on 2024-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_benifits_and_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benifits_and_features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommandation',
            field=models.TextField(null=True),
        ),
    ]
