# Generated by Django 5.0.1 on 2024-06-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productcollection_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
