# Generated by Django 5.0.1 on 2024-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productcollection_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='demonstration_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcollection',
            name='technical_specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
