# Generated by Django 5.0.1 on 2024-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productcollection_demonstration_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='demonstration_video',
            field=models.URLField(default=False, help_text='0=show,1=Hidden'),
        ),
    ]
