# Generated by Django 5.0.1 on 2024-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productcollection_demonstration_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='demonstration_video',
            field=models.URLField(blank=True, help_text='0=show,1=Hidden', null=True),
        ),
    ]
