# Generated by Django 5.0.1 on 2024-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_productcollection_demonstration_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
