# Generated by Django 5.0.1 on 2024-10-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productcollection_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopBrands',
        ),
    ]
