# Generated by Django 5.0.1 on 2024-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_delete_topbrands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
